Repository CodeOfDutyJS/documentazione, pull requests merged in 2020-12, with the labels that each got.

#3 Aggiornamento replace glossario
  _glo_replace.py
Labels: enhancement

#4 Update compile-studio-fattibilita.yml
  .github/workflows/compile-studio-fattibilita.yml
Labels: bug

#8 Aggiornato script per glossario
  _glo_replace.py
  studio-di-fattibilita.pdf
  studio-di-fattibilita/main.pdf
Labels: enhancement

#32 Flori/verbali
  glossario.txt
  verbali/_config/config.tex
  verbali/_config/package.tex
  verbali/_template/changelog.tex
  verbali/_template/images/logo.png
  verbali/_template/images/logo_crop.png
  verbali/_template/tables/informazioni_generali_table.tex
  verbali/_template/tables/riepilogo_decisioni_table.tex
  verbali/_template/title_page.tex
  verbali/template-documento-verbale/README.md
  verbali/template-documento-verbale/main.tex
  verbali/template-documento-verbale/source/changelog.tex
  verbali/template-documento-verbale/source/sections/informazion_generali.tex
  verbali/template-documento-verbale/source/sections/riepilogo_decisioni.tex
  verbali/template-documento-verbale/source/sections/verbale_incontro.tex
  verbali/template-documento-verbale/source/title_page.tex
  verbali/verbale-interno_2020-12-09/README.md
  verbali/verbale-interno_2020-12-09/main.tex
  verbali/verbale-interno_2020-12-09/source/changelog.tex
  verbali/verbale-interno_2020-12-09/source/sections/informazion_generali.tex
  verbali/verbale-interno_2020-12-09/source/sections/riepilogo_decisioni.tex
  verbali/verbale-interno_2020-12-09/source/sections/verbale_incontro.tex
  verbali/verbale-interno_2020-12-09/source/title_page.tex
  verbali/verbale-interno_2020-12-16/README.md
  verbali/verbale-interno_2020-12-16/main.tex
  verbali/verbale-interno_2020-12-16/source/changelog.tex
  verbali/verbale-interno_2020-12-16/source/sections/informazion_generali.tex
  verbali/verbale-interno_2020-12-16/source/sections/riepilogo_decisioni.tex
  verbali/verbale-interno_2020-12-16/source/sections/verbale_incontro.tex
  verbali/verbale-interno_2020-12-16/source/title_page.tex
Labels: verbali
